### ISSUE TITLE
Object 0x37df76627a30 is not a subclass of GObject_Object, it's a Object

### ISSUE THREAD

**Issue by artieeffim** [phavekes/gnome-extension-all-ip-addresses#3]
Running PoP!_OS 22.04 LTS, GNOME 42.0, X11
This extension errors out in newest version.

Was running fine in 21.10.

might be relevant:
 [ 7650.044822] gnome-shell[74195]: segfault at 80 ip 00007f68cb9ad074 sp 00007ffe97178618 error 4 in libmutter-10.so.0.0.0[7f68cb90a000+142000]

Don't know how to generate logging or debugging, but happy to help if you can provide commands.

**Comment by captainnatebeard** [comment]
I've created a fork that fixes this problem.  You can find it here:
https://extensions.gnome.org/extension/3994/all-ip-addresses/

**Comment by phavekes** [comment]
@captainnatebeard could you create a PR?
