### ISSUE TITLE
Gnome 43 compatible

### ISSUE THREAD

**Issue by MegaIO** [phavekes/gnome-extension-all-ip-addresses#7]
I would really like to have your extension for Gnome 43. Fedora and Ubuntu are already out.

**Comment by phavekes** [comment]
I'll look in to making it compatible next week

**Comment by phavekes** [comment]
That was an easy fix:
https://github.com/phavekes/gnome-extension-all-ip-addresses/commit/6dd21f6bc3abd0c6c2f6c6cf228ef75efeb1a9df
Available in [the extension store](https://extensions.gnome.org/) soon
