### ISSUE TITLE
IP6 is showing ip address from vpn, while vpn ipaddress is missing

### ISSUE THREAD

**Issue by birdie1** [phavekes/gnome-extension-all-ip-addresses#8]
The extension shows wrong addresses:
- IP6 is taking its address from vpn instead of wifi or cable
- VPN is not showing any address at all

![image](https://user-images.githubusercontent.com/33814912/207386580-db511c80-145d-4fe1-9a02-8326a0dffa01.png)
![image](https://user-images.githubusercontent.com/33814912/207386652-35052662-c7a7-4d44-8790-c32a9e0292d5.png)
![image](https://user-images.githubusercontent.com/33814912/207387419-36cecf3f-a803-480d-a334-1db29c726a4d.png)
![image](https://user-images.githubusercontent.com/33814912/207386766-394e85c6-262c-4aa6-a33e-b788cb452d85.png)
![image](https://user-images.githubusercontent.com/33814912/207386835-bb5b0c88-455a-45c5-ba38-f0e7279ca0a7.png)

**Comment by phavekes** [comment]
This will fix the `vpn0` issue: https://github.com/phavekes/gnome-extension-all-ip-addresses/commit/043e480a9b40526826b98c6df6053fa96c62098b

**Comment by phavekes** [comment]
`IP6` will show the address of the default route for ipv6 traffic, so this behaviour is expected.
I could however add different information for WAN IPv6 and VPN IPv6
