### ISSUE TITLE
GNOME 44

### ISSUE THREAD

**Issue by MarcMichalsky** [phavekes/gnome-extension-all-ip-addresses#9]
Maybe it's as easy as with GNOME 43 https://github.com/phavekes/gnome-extension-all-ip-addresses/commit/6dd21f6bc3abd0c6c2f6c6cf228ef75efeb1a9df.

**Comment by phavekes** [comment]
Fixed in https://github.com/phavekes/gnome-extension-all-ip-addresses/commit/f2f14deb875e43c2288aaf1c6a3be6f131695904

**Comment by MarcMichalsky** [comment]
Tanks!
